[project]
name = "ai2-0to2-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.18.0",
    "google-genai>=1.30.0",
    "notebook>=7.5.3",
    "python-dotenv==1.1.1",
    "openai>=1.98.0",
    "streamlit>=1.49.0",
    "openai-agents>=0.2.9",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
